language: python
python:
  #- "2.6"
  #- "2.7"
  #- "3.2"
  #- "3.3"
  - "3.5"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  #- "pypy"
# command to install dependencies
install:
  - pip install .
  #- pip install -r requirements.txt
# command to run tests
script: nosetests

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/37abdd7a025594a1a987
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
